version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dewurugenuvin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dewurugenuvin -d library"]
      interval: 10s
      timeout: 5s
      retries: 5

  library-service:
    build: .
    container_name: library-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: dewurugenuvin
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      postgres:
        condition: service_healthy
